name: CI

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]
  workflow_dispatch:

jobs:
  buildAndroid:
    runs-on: ubuntu-latest
    env:
      ANDROID_NDK_HOME: ${{ steps.setup-ndk.outputs.ndk-path }}

    steps:
      - name: Checkout
        uses: actions/checkout@v2

      - name: Setup Android NDK
        uses: nttld/setup-ndk@v1
        id: setup-ndk
        with:
          ndk-version: r21e

      - name: Setup Java JDK
        uses: actions/setup-java@v3
        with:
          java-version: '11'
          distribution: 'temurin'

      - name: Setup Android SDK
        uses: android-actions/setup-android@v2

      - name: Setup Haxe
        uses: krdlab/setup-haxe@v1.1.5
        with:
          haxe-version: 4.2.5

      - name: Install Haxelib
        run: |
          haxelib setup ~/haxelib
          haxelib install hxcpp > /dev/null
          haxelib --quiet install lime
          haxelib --quiet install openfl
          haxelib --quiet install flixel
          haxelib --quiet --always run lime setup flixel
          haxelib --quiet install flixel-ui
          haxelib --quiet install flixel-addons
          haxelib git linc_luajit https://github.com/MAJigsaw77/linc_luajit.git --quiet || true
          haxelib git extension-androidtools https://github.com/MAJigsaw77/extension-androidtools.git --quiet || true
          haxelib list

      - name: Create Version Tag
        run: echo "${{ github.run_id }}" > VERSION

      - name: Setup Lime
        run: |
          haxelib run lime setup -alias -y
          haxelib run lime config ANDROID_SDK $ANDROID_HOME
          haxelib run lime config ANDROID_NDK_ROOT $ANDROID_NDK_HOME
          haxelib run lime config JAVA_HOME $JAVA_HOME
          haxelib run lime config ANDROID_SETUP true

      - name: Compile
        run: haxelib run lime build android --app-version="4.0.0-${{ github.run_id }}"

      - name: Verify APK
        run: ls -l export/release/android/bin/app/build/outputs/apk/debug

      - name: Publish Artifact
        uses: actions/upload-artifact@v2
        with:
          name: androidBuild
          path: export/release/android/bin/app/build/outputs/apk/debug
